### ISSUE TITLE
Insufficient Quota API Limitation 

### ISSUE THREAD

**Issue by sercuz** [slincoln-aiq/DetectIQ#3]
It would be more clear if you mentioned which API key type is preferred, and what is the required quota at minimum to utilize the LLM. I used service account API Key and original API key but it did not work due to insufficient quota when creating victor store from the app config GUI page.

"Failed to create vector store: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
Error creating Sigma vector store: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
Error creating vectorstore: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
Internal Server Error: /app-config/create-vectorstore/"

**Comment by cyberphor** [comment]
@sercuz I got this error before with another LLM-based app. I was able to fix it by setting the quota for my OpenAI API key to a few US dollars. 

Also, can you clarify what you mean by key type? From my understanding, DetectIQ currently uses the same OpenAI API key generated by default.

**Comment by sercuz** [comment]
@cyberphor Thank you for pointing it out! It is resolved now.

Key type (there is service account and normal user API keys), Much appreciated, cheers.
